# Header
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links
  About: /about
logo: https://nurui.fueko.net/content/images/2018/12/nurui.svg


# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
large_legnth: 20
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# commit
commit:
  valine: true
